# Generated by Django 5.1.3 on 2024-11-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReliefSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('individual_dependents', 'Individual & Dependent Relatives'), ('education_fee', 'Education Fee for Self'), ('disabled_equipment', 'Equipment for Disabled Person'), ('medical_self_family', 'Medical Expenses for Self, Spouse or Children'), ('medical_parent', 'Medical Expenses for Parent'), ('epf', 'EPF'), ('socso', 'SOCSO'), ('life_insurance', 'Life Insurance'), ('education_medical_insurance', 'Education & Medical Insurance'), ('prs', 'Private Retirement Scheme (PRS)'), ('sspn', 'SSPN'), ('lifestyle', 'Lifestyle (Reading Materials, Electronics, Internet, etc.)'), ('lifestyle_sports', 'Lifestyle - Additional Relief for Sports Activity'), ('ev_charging', 'Electric Vehicle Charging Facilities'), ('donation_gift', 'Donation / Gift')], max_length=50, unique=True)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
