# Generated by Django 5.1.3 on 2024-11-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_taxreliefsubcategory_maximum_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('transaction_description', models.TextField()),
                ('transaction_remarks', models.TextField(blank=True, null=True)),
                ('amount_including_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('tax_relief_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.taxreliefsubcategory')),
            ],
        ),
    ]
