# Generated by Django 5.1.3 on 2024-11-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_usertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
