# Generated by Django 5.1.3 on 2024-11-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_usertransaction_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_invoice_reference_number', models.CharField(max_length=100, unique=True)),
                ('upload_document_reference_number', models.CharField(max_length=100, unique=True)),
                ('item_description', models.TextField()),
                ('amount_including_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='mysite.usertransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='document', serialize=False, to='mysite.transactioninvoice', to_field='upload_document_reference_number')),
                ('path', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='e_invoice', serialize=False, to='mysite.transactioninvoice', to_field='e_invoice_reference_number')),
                ('file_path', models.FileField(upload_to='e_invoices/')),
            ],
        ),
    ]
