# Generated by Django 5.1.3 on 2024-11-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_usertransaction_tax_relief_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='uploaded_invoices/')),
            ],
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='e_invoice_reference_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.einvoice'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.usertransaction'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='upload_document_reference_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.uploadedinvoice'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
