# Generated by Django 5.1.3 on 2024-11-30 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_uploadedinvoice_remove_usertransaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='e_invoice_reference_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.einvoice'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='upload_document_reference_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.uploadedinvoice'),
        ),
    ]
