# Generated by Django 5.1.3 on 2024-11-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_transactionitem_e_invoice_reference_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('individual_dependents', 'Individual & Dependent Relatives'), ('education_fee', 'Education Fee for Self'), ('disabled_equipment', 'Equipment for Disabled Person'), ('medical_self_family', 'Medical Expenses for Self, Spouse or Children'), ('medical_parent', 'Medical Expenses for Parent'), ('epf', 'EPF'), ('socso', 'SOCSO'), ('life_insurance', 'Life Insurance'), ('education_medical_insurance', 'Education & Medical Insurance'), ('prs', 'Private Retirement Scheme (PRS)'), ('sspn', 'SSPN'), ('lifestyle', 'Lifestyle (Reading Materials, Electronics, Internet, etc.)'), ('lifestyle_sports', 'Lifestyle - Additional Relief for Sports Activity'), ('ev_charging', 'Electric Vehicle Charging Facilities'), ('donation_gift', 'Donation / Gift')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
