# Generated by Django 5.1.3 on 2024-11-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='e_invoice_reference_number',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='upload_document_reference_number',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='transaction',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='invoices/')),
                ('is_e_invoice', models.BooleanField()),
                ('user_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.usertransaction')),
            ],
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.invoice'),
        ),
        migrations.DeleteModel(
            name='EInvoice',
        ),
        migrations.DeleteModel(
            name='UploadedInvoice',
        ),
    ]
