# Generated by Django 5.1.3 on 2024-11-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_remove_transactionitem_e_invoice_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='is_deductable',
            field=models.BooleanField(default=False),
        ),
    ]
