# Generated by Django 5.1.3 on 2024-11-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_usertransaction_is_deductable'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.usertransaction'),
            preserve_default=False,
        ),
    ]
